<ol>
    <li>Any school in Monmouth or Ocean County with students in grades 9, 10, 11, or 12 may participate in the All-Shore Chorus.</li>
    <li>Each member school (that is, each school which separately pays a membership fee) may send a total of up to 25 students to auditions. If several schools share a membership (such as a junior and senior high school) the number of students sent from all of the schools combined may total up to 25 students. Schools sending more than 25 students to auditions will have all of their students disqualified.</li>
    <li>All students from a school whose Choral Director does not submit the proper membership forms and audition registration on time are ineligible to participate in the All-Shore Chorus and will not be permitted to audition.</li>
    <li>All Students from any school are automatically ineligible to participate in All-Shore Chorus if a qualified judge from the school is not present for the entire day of auditions. This is normally the Director of the school chorus. Directors who can be present for only a part of the evening must arrange for a substitute for the remainder of the evening. Each member school must be represented by a separate judge. No exceptions will be made.</li>
    <li>All Students must complete a Student Audition Form and present it at the registration table the day of auditions. If the form is incomplete, the student will not be allowed to audition.</li>
    <li>All students auditioning for the All-Shore Chorus must be regular members of the choir/chorus of their own school. Only students who are well qualified, well prepared, of good character, and of a reliable nature should be permitted to audition. Each student who sings in the All-Shore Chorus is required to sign a membership agreement regarding the responsibilities of membership in the chorus. This must also be signed by their parent/guardian, school principal, and Choral Director.</li>
    <li>An auditioning student may attend either a junior or senior high school, and she/he must be in grades 9-12. The student may audition for any one voice part. She/he will not be re-auditioned for another part. There is no restriction against male altos or female tenors.</li>
    <li>Any student will be disqualified who sings or makes noise in the hallways during auditions. Students must not wear any school jackets, T-shirts, uniforms, etc., which would identify their school to the judges. They must not wear any pins, hats, etc., that would identify them as members of All-State, All-Shore, Band, Chorus, Orchestra, etc., or as the recipient of any special musical honor or award.</li>
    <li>Schedule preference will be given schools whose audition information forms are received first. Once an audition time is assigned, students will be required to audition at the designated time.</li>
    <li>Students from the same school must register together and on time. Exceptions may be made if arrangements are made with the Auditions Manager in advance. Once auditions have been closed, they will not be re-opened for late-comers.</li>
    <li>Results of the auditions will be emailed to the schools as soon as computations are completed. The Choral Director will receive the audition forms and score sheets for each student who auditioned.</li>
    <li>A complete schedule of rehearsal dates is posted on the All-Shore Chorus web site.</li>
    <li>Each Choral Director who has any students accepted into All-Shore Chorus MUST assist at one rehearsal minimum or his/her students will not be permitted to audition the following year.</li>
</ol>
